name = "EnvironmentsRender"
uuid = "c300cdb7-4d3c-4ff5-92e1-50de43cb48fa"
authors = ["Grzegorz Orzechowski <2590699+gorzech@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Environments = "3a0e23c7-c015-460e-b903-d2dac87c3752"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
GLMakie = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
